/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.woolford;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PingRecordAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5238150977211888208L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PingRecordAvro\",\"namespace\":\"io.woolford\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"isReachable\",\"type\":\"boolean\"},{\"name\":\"localInetAddress\",\"type\":\"string\"},{\"name\":\"remoteInetAddress\",\"type\":\"string\"},{\"name\":\"responseMicroseconds\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long timestamp;
  @Deprecated public boolean isReachable;
  @Deprecated public java.lang.CharSequence localInetAddress;
  @Deprecated public java.lang.CharSequence remoteInetAddress;
  @Deprecated public long responseMicroseconds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PingRecordAvro() {}

  /**
   * All-args constructor.
   * @param timestamp The new value for timestamp
   * @param isReachable The new value for isReachable
   * @param localInetAddress The new value for localInetAddress
   * @param remoteInetAddress The new value for remoteInetAddress
   * @param responseMicroseconds The new value for responseMicroseconds
   */
  public PingRecordAvro(java.lang.Long timestamp, java.lang.Boolean isReachable, java.lang.CharSequence localInetAddress, java.lang.CharSequence remoteInetAddress, java.lang.Long responseMicroseconds) {
    this.timestamp = timestamp;
    this.isReachable = isReachable;
    this.localInetAddress = localInetAddress;
    this.remoteInetAddress = remoteInetAddress;
    this.responseMicroseconds = responseMicroseconds;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return isReachable;
    case 2: return localInetAddress;
    case 3: return remoteInetAddress;
    case 4: return responseMicroseconds;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: isReachable = (java.lang.Boolean)value$; break;
    case 2: localInetAddress = (java.lang.CharSequence)value$; break;
    case 3: remoteInetAddress = (java.lang.CharSequence)value$; break;
    case 4: responseMicroseconds = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'isReachable' field.
   * @return The value of the 'isReachable' field.
   */
  public java.lang.Boolean getIsReachable() {
    return isReachable;
  }

  /**
   * Sets the value of the 'isReachable' field.
   * @param value the value to set.
   */
  public void setIsReachable(java.lang.Boolean value) {
    this.isReachable = value;
  }

  /**
   * Gets the value of the 'localInetAddress' field.
   * @return The value of the 'localInetAddress' field.
   */
  public java.lang.CharSequence getLocalInetAddress() {
    return localInetAddress;
  }

  /**
   * Sets the value of the 'localInetAddress' field.
   * @param value the value to set.
   */
  public void setLocalInetAddress(java.lang.CharSequence value) {
    this.localInetAddress = value;
  }

  /**
   * Gets the value of the 'remoteInetAddress' field.
   * @return The value of the 'remoteInetAddress' field.
   */
  public java.lang.CharSequence getRemoteInetAddress() {
    return remoteInetAddress;
  }

  /**
   * Sets the value of the 'remoteInetAddress' field.
   * @param value the value to set.
   */
  public void setRemoteInetAddress(java.lang.CharSequence value) {
    this.remoteInetAddress = value;
  }

  /**
   * Gets the value of the 'responseMicroseconds' field.
   * @return The value of the 'responseMicroseconds' field.
   */
  public java.lang.Long getResponseMicroseconds() {
    return responseMicroseconds;
  }

  /**
   * Sets the value of the 'responseMicroseconds' field.
   * @param value the value to set.
   */
  public void setResponseMicroseconds(java.lang.Long value) {
    this.responseMicroseconds = value;
  }

  /**
   * Creates a new PingRecordAvro RecordBuilder.
   * @return A new PingRecordAvro RecordBuilder
   */
  public static io.woolford.PingRecordAvro.Builder newBuilder() {
    return new io.woolford.PingRecordAvro.Builder();
  }

  /**
   * Creates a new PingRecordAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PingRecordAvro RecordBuilder
   */
  public static io.woolford.PingRecordAvro.Builder newBuilder(io.woolford.PingRecordAvro.Builder other) {
    return new io.woolford.PingRecordAvro.Builder(other);
  }

  /**
   * Creates a new PingRecordAvro RecordBuilder by copying an existing PingRecordAvro instance.
   * @param other The existing instance to copy.
   * @return A new PingRecordAvro RecordBuilder
   */
  public static io.woolford.PingRecordAvro.Builder newBuilder(io.woolford.PingRecordAvro other) {
    return new io.woolford.PingRecordAvro.Builder(other);
  }

  /**
   * RecordBuilder for PingRecordAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PingRecordAvro>
    implements org.apache.avro.data.RecordBuilder<PingRecordAvro> {

    private long timestamp;
    private boolean isReachable;
    private java.lang.CharSequence localInetAddress;
    private java.lang.CharSequence remoteInetAddress;
    private long responseMicroseconds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.woolford.PingRecordAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isReachable)) {
        this.isReachable = data().deepCopy(fields()[1].schema(), other.isReachable);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.localInetAddress)) {
        this.localInetAddress = data().deepCopy(fields()[2].schema(), other.localInetAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.remoteInetAddress)) {
        this.remoteInetAddress = data().deepCopy(fields()[3].schema(), other.remoteInetAddress);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.responseMicroseconds)) {
        this.responseMicroseconds = data().deepCopy(fields()[4].schema(), other.responseMicroseconds);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PingRecordAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(io.woolford.PingRecordAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isReachable)) {
        this.isReachable = data().deepCopy(fields()[1].schema(), other.isReachable);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.localInetAddress)) {
        this.localInetAddress = data().deepCopy(fields()[2].schema(), other.localInetAddress);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.remoteInetAddress)) {
        this.remoteInetAddress = data().deepCopy(fields()[3].schema(), other.remoteInetAddress);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.responseMicroseconds)) {
        this.responseMicroseconds = data().deepCopy(fields()[4].schema(), other.responseMicroseconds);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isReachable' field.
      * @return The value.
      */
    public java.lang.Boolean getIsReachable() {
      return isReachable;
    }

    /**
      * Sets the value of the 'isReachable' field.
      * @param value The value of 'isReachable'.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder setIsReachable(boolean value) {
      validate(fields()[1], value);
      this.isReachable = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isReachable' field has been set.
      * @return True if the 'isReachable' field has been set, false otherwise.
      */
    public boolean hasIsReachable() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isReachable' field.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder clearIsReachable() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'localInetAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocalInetAddress() {
      return localInetAddress;
    }

    /**
      * Sets the value of the 'localInetAddress' field.
      * @param value The value of 'localInetAddress'.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder setLocalInetAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.localInetAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'localInetAddress' field has been set.
      * @return True if the 'localInetAddress' field has been set, false otherwise.
      */
    public boolean hasLocalInetAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'localInetAddress' field.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder clearLocalInetAddress() {
      localInetAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'remoteInetAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getRemoteInetAddress() {
      return remoteInetAddress;
    }

    /**
      * Sets the value of the 'remoteInetAddress' field.
      * @param value The value of 'remoteInetAddress'.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder setRemoteInetAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.remoteInetAddress = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'remoteInetAddress' field has been set.
      * @return True if the 'remoteInetAddress' field has been set, false otherwise.
      */
    public boolean hasRemoteInetAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'remoteInetAddress' field.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder clearRemoteInetAddress() {
      remoteInetAddress = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'responseMicroseconds' field.
      * @return The value.
      */
    public java.lang.Long getResponseMicroseconds() {
      return responseMicroseconds;
    }

    /**
      * Sets the value of the 'responseMicroseconds' field.
      * @param value The value of 'responseMicroseconds'.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder setResponseMicroseconds(long value) {
      validate(fields()[4], value);
      this.responseMicroseconds = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'responseMicroseconds' field has been set.
      * @return True if the 'responseMicroseconds' field has been set, false otherwise.
      */
    public boolean hasResponseMicroseconds() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'responseMicroseconds' field.
      * @return This builder.
      */
    public io.woolford.PingRecordAvro.Builder clearResponseMicroseconds() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PingRecordAvro build() {
      try {
        PingRecordAvro record = new PingRecordAvro();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.isReachable = fieldSetFlags()[1] ? this.isReachable : (java.lang.Boolean) defaultValue(fields()[1]);
        record.localInetAddress = fieldSetFlags()[2] ? this.localInetAddress : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.remoteInetAddress = fieldSetFlags()[3] ? this.remoteInetAddress : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.responseMicroseconds = fieldSetFlags()[4] ? this.responseMicroseconds : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
